# Generated by Django 3.2.13 on 2022-07-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('identifier', models.SlugField(blank=True, max_length=20, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
